[package]
name = "ordering-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faer = "0.23.2"
num-complex = "0.4.6"

[[bin]]
name = "ordering-rs"
path = "main.rs"
